---
name: buildDockerImage

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main
    paths:
      - whisper_service/*
      - tests/*
      - Dockerfile
      - requirements.txt
      - .github/workflows/buildDockerImage.yml
  pull_request:
    branches:
      - main
    paths:
      - whisper_service/*
      - tests/*
      - Dockerfile
      - requirements.txt
      - .github/workflows/buildDockerImage.yml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: brandonmcclure/whisper_service
  JUST_IMAGE_NAME: whisper_service

jobs:
  buildDockerImage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Log in to the Github Container registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
        with:
          registry: ghcr.io

          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
        with:
          username: bmcclure89

          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: github.ref == 'refs/heads/main'
      - name: Extract metadata (tags, labels) for Docker
        id: meta_github
        uses: docker/metadata-action@a64d0487d7069df33b279515d35d60fa80e2ea62
        with:
          tags: |
            type=ref,event=pr
            type=ref,event=branch
            type=sha,format=long
            type=raw,value=latest
          images: |
            ghcr.io/brandonmcclure/whisper_service/${{ env.IMAGE_NAME }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta_dockerhub
        uses: docker/metadata-action@a64d0487d7069df33b279515d35d60fa80e2ea62
        with:
          tags: |
            type=ref,event=pr
            type=ref,event=branch
            type=sha,format=long
            type=raw,value=latest
          images: |
            bmcclure89/${{ env.JUST_IMAGE_NAME }}
        if: github.ref == 'refs/heads/main'
      - name: Build Docker image (non main branch)
        uses: docker/build-push-action@af64c4e18f18907592d87ebdea2882bc1f27a07a
        if: github.ref != 'refs/heads/main'
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta_github.outputs.tags }}
          labels: ${{ steps.meta_github.outputs.labels }} 
      - name: Build and push Docker image (main branch)
        uses: docker/build-push-action@af64c4e18f18907592d87ebdea2882bc1f27a07a
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta_dockerhub.outputs.tags }}
          labels: ${{ steps.meta_dockerhub.outputs.labels }}
      - name: Build and push Docker image (main branch)
        uses: docker/build-push-action@af64c4e18f18907592d87ebdea2882bc1f27a07a
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta_github.outputs.tags }}
          labels: ${{ steps.meta_github.outputs.labels }}
