---
name: buildDockerImage

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main
    paths:
      - whisper_service/*
      - tests/*
      - Dockerfile
      - requirements.txt
      - .github/workflows/buildDockerImage.yml
  pull_request:
    branches:
      - main
    paths:
      - whisper_service/*
      - tests/*
      - Dockerfile
      - requirements.txt
      - .github/workflows/buildDockerImage.yml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: brandonmcclure/whisper_service
  JUST_IMAGE_NAME: whisper_service

jobs:
  buildDockerImage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Log in to the Github Container registry
        uses: docker/login-action@7ca345011ac4304463197fac0e56eab1bc7e6af0
        with:
          registry: ghcr.io

          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@7ca345011ac4304463197fac0e56eab1bc7e6af0
        with:
          username: bmcclure89

          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: github.ref == 'refs/heads/main'
      - name: Extract metadata (tags, labels) for Docker
        id: meta_github
        uses: docker/metadata-action@b53be03109c4ef6f6cc7aa545b84b17a7fe51c1e
        with:
          tags: |
            type=ref,event=pr
            type=ref,event=branch
            type=sha,format=long
            type=raw,value=latest
          images: |
            ghcr.io/brandonmcclure/whisper_service/${{ env.IMAGE_NAME }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta_dockerhub
        uses: docker/metadata-action@b53be03109c4ef6f6cc7aa545b84b17a7fe51c1e
        with:
          tags: |
            type=ref,event=pr
            type=ref,event=branch
            type=sha,format=long
            type=raw,value=latest
          images: |
            bmcclure89/${{ env.JUST_IMAGE_NAME }}
        if: github.ref == 'refs/heads/main'
      - name: Build Docker image (non main branch)
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355
        if: github.ref != 'refs/heads/main'
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta_github.outputs.tags }}
          labels: ${{ steps.meta_github.outputs.labels }} 
      - name: Build and push Docker image (main branch)
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta_dockerhub.outputs.tags }}
          labels: ${{ steps.meta_dockerhub.outputs.labels }}
      - name: Build and push Docker image (main branch)
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta_github.outputs.tags }}
          labels: ${{ steps.meta_github.outputs.labels }}
