---
name: buildDockerImage

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main
    paths:
      - whisper_service/*
      - tests/*
      - Dockerfile
      - requirements.txt
      - .github/workflows/buildDockerImage.yml
  pull_request:
    branches:
      - main
    paths:
      - whisper_service/*
      - tests/*
      - Dockerfile
      - requirements.txt
      - .github/workflows/buildDockerImage.yml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: brandonmcclure/whisper_service
  JUST_IMAGE_NAME: whisper_service

jobs:
  buildDockerImage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Log in to the Github Container registry
        uses: docker/login-action@1f36f5b7a2d2f7bfd524795fc966e6d88c37baa9
        with:
          registry: ghcr.io

          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@1f36f5b7a2d2f7bfd524795fc966e6d88c37baa9
        with:
          username: bmcclure89

          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: github.ref == 'refs/heads/main'
      - name: Extract metadata (tags, labels) for Docker
        id: meta_github
        uses: docker/metadata-action@d31acd50653ded455ab8972a1eb9a656b0aef94a
        with:
          tags: |
            type=ref,event=pr
            type=ref,event=branch
            type=sha,format=long
            type=raw,value=latest
          images: |
            ghcr.io/brandonmcclure/whisper_service/${{ env.IMAGE_NAME }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta_dockerhub
        uses: docker/metadata-action@d31acd50653ded455ab8972a1eb9a656b0aef94a
        with:
          tags: |
            type=ref,event=pr
            type=ref,event=branch
            type=sha,format=long
            type=raw,value=latest
          images: |
            bmcclure89/${{ env.JUST_IMAGE_NAME }}
        if: github.ref == 'refs/heads/main'
      - name: Build Docker image (non main branch)
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75
        if: github.ref != 'refs/heads/main'
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta_github.outputs.tags }}
          labels: ${{ steps.meta_github.outputs.labels }} 
      - name: Build and push Docker image (main branch)
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta_dockerhub.outputs.tags }}
          labels: ${{ steps.meta_dockerhub.outputs.labels }}
      - name: Build and push Docker image (main branch)
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta_github.outputs.tags }}
          labels: ${{ steps.meta_github.outputs.labels }}
